#!/bin/bash
#
# StatsD
#
# chkconfig: 3 50 50
# description: StatsD init.d
. /etc/rc.d/init.d/functions

DESC="redis-statsd-reporter"
NAME="redis-statsd-reporter"
DAEMON="/usr/local/sbin/redis-statsd-reporter"
pidfile=/var/run/redis-statsd-reporter.pid
lockfile=/var/lock/subsys/redis-statsd-reporter
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Determine if we can use the -p option to daemon, killproc, and status.
# RHEL < 5 can't.
if status | grep -q -- '-p' 2>/dev/null; then
    daemonopts="--pidfile $pidfile"
    pidopts="-p $pidfile"
fi

start() {
  echo -n $"Starting $NAME: "
  # See if it's already running. Look *only* at the pid file.
  if [ -f ${pidfile} ]; then
    failure "PID file exists for redis-statsd-reporter"
    RETVAL=1
  else
    # Run as process
    $DAEMON ${RPTJS} ${RSRPT_CONFIG_DIR} ${RSRPT_LOGFILE} &
    RETVAL=$?
    # Store PID
    echo $! > ${pidfile}

    # Success
    [ $RETVAL = 0 ] && success "redis-statsd-reporter started"
  fi

  echo
  return $RETVAL
}

stop() {
  echo -n $"Stopping $NAME: "
  killproc -p ${pidfile}
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && rm -f ${pidfile}
}

# See how we were called.
case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  status -p ${pidfile} ${prog}
  RETVAL=$?
  ;;
  restart)
  stop
  start
  ;;
  condrestart)
  if [ -f ${pidfile} ] ; then
    stop
    start
  fi
  ;;
  *)
  echo $"Usage: $prog {start|stop|restart|condrestart|status}"
  exit 1
esac

exit $RETVAL
